### ISSUE TITLE
[meta] Automatically release API documentation

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/Hackathons#9]
#### What?

Each time we publish a new tag on a core project, we should launch a Travis-CI process to release a new version of the API documentation.

#### Maybe relevant documentation

- How they made it with TodoMVC https://github.com/tastejs/todomvc/issues/972
- Some tutorial http://rmcgibbo.org/posts/deploying-with-travis-ci-and-s3/

#### Related issues

- https://github.com/yeoman/generator/issues/673
- https://github.com/yeoman/environment/issues/9

#### Stretch goal

Release yeoman.io each time there's a change. See https://github.com/yeoman/yeoman.io/issues/344

**Comment by arthurvr** [comment]
This is all setup and works like a charm. Is there some reason this issue is staying open?

**Comment by ahmadnassri** [comment]
this was opened as an idea for a hackathon, i believe its good to close now.

**Comment by SBoudrias** [comment]
This is actually not done. Only yeoman.io is automatically build and released. Our API documentation still rely on manual process.

Help fixing this is warmly welcomed!
